### ISSUE TITLE
Cannot compile (Help needed)

### ISSUE THREAD

**Issue by bospre** [lewisxhe/esp32-camera-bme280#1]
Hello,
after getting all needed libraries I still can not compile.
Maybe it is an issue regarding the arduino ESP-release.
I am using the final release V1.01.

The error messages are (shortened)

In file included from ...hardware\esp32\1.0.1/tools/sdk/include/esp32-camera/esp_camera.h:70:0,
                 from esp32-camera-bme280\esp32-camera-bme280.ino:6:
...\hardware\esp32\1.0.1/tools/sdk/include/esp32-camera/sensor.h:83:24: error: conflicting declaration 'typedef struct _sensor sensor_t'

In file included from \libraries\Adafruit_BME280_Library/Adafruit_BME280.h:26:0,
                 from \esp32-camera-bme280\esp32-camera-bme280.ino:5:

... libraries\Adafruit_Sensor/Adafruit_Sensor.h:139:3: note: previous declaration as 'typedef struct sensor_t sensor_t'

 } sensor_t;
In file included from ...\hardware\esp32\1.0.1/tools/sdk/include/esp32-camera/esp_camera.h:70:0,
                 from \esp32-camera-bme280\esp32-camera-bme280.ino:6:
...\hardware\esp32\1.0.1/tools/sdk/include/esp32-camera/sensor.h:122:3: error: conflicting declaration 'typedef struct _sensor sensor_t'

esp32-camera-bme280:67:8: error: 'struct sensor_t' has no member named 'set_vflip'
     s->set_vflip(s, en);

esp32-camera-bme280:181:8: error: 'struct sensor_t' has no member named 'set_framesize'

     s->set_framesize(s, FRAMESIZE_QVGA);

exit status 1
'struct sensor_t' has no member named 'set_vflip'

**Comment by bospre** [comment]
OK, it was my fault. I did not follow the instructions.
As mentioned, you have to comment out the line
#include <Adafruit_Sensor.h> in the library <Adafruit_BME280.h>
Then it compiles and run.
Another thing to mention: this board is not yet included in the arduino boardmanager. The sketch does not run with the esp32dev module choosen. You have to choose "ESP32 Wrover Module".

**Comment by collote69** [comment]
Hello sorry, I have the same error but I comment what you say and I use ESP32 Wrover Module but it tells me an error of compiling a card, I do not know what to do thanks.

**Comment by bospre** [comment]
If you want help, it would be a good idea to provide more details.

**Comment by collote69** [comment]
esp32-camera-bme280:5:29: error: Adafruit_Sensor.h: No such file or directory

Several libraries were found for "WiFi.h"
compilation terminated.

used: C:\Users\home\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.1\libraries\WiFi
not used: C:\Users\home\Pictures\esp32\arduino-1.8.8\libraries\WiFi
exit status 1
Adafruit_Sensor.h: No such file or directory
and installed the sensor libraries but I do not know if I do it right I'm a bit of a rookie with this

**Comment by albaric** [comment]
HI 

I have the same problem, and I have this message 👍 
Archiving built core (caching) in: /var/folders/6y/v9jwdbg54ld819nfp_vk1p4r0000gn/T/arduino_cache_599702/core/core_espressif_esp32_esp32wrover_PartitionScheme_default,FlashMode_qio,FlashFreq_80,UploadSpeed_921600,DebugLevel_none_e77d1463fb70e59877f79455d426ae13.a
sketch/esp32-camera-bme280.ino.cpp.o:(.literal._Z5setupv+0x6c): undefined reference to `startCameraServer()'
sketch/esp32-camera-bme280.ino.cpp.o: In function `setup()':
/Users/gaelle/Downloads/esp32-camera-bme280-master/esp32-camera-bme280/esp32-camera-bme280.ino:289: undefined reference to `startCameraServer()'
collect2: error: ld returned 1 exit status
exit status 1
Erreur de compilation pour la carte ESP32 Wrover Module


Thanks for your help

**Comment by philgree** [comment]
@bospre - thanks, I made the same mistake as you with similar results. Your comment put me back on the straight and narrow and now it's working!

**Comment by diegozalez** [comment]
[Adafruit_BME280_Library.zip](https://github.com/lewisxhe/esp32-camera-series/files/4449350/Adafruit_BME280_Library.zip)
I hapen to come across the same problem and i got to delete all de adafruit sensor in the BME280 library, i have attach the library files working for me
