### ISSUE TITLE
Powering t-camera v1.6.2 (hardware not software issue)

### ISSUE THREAD

**Issue by Bazmundi** [lewisxhe/esp32-camera-bme280#25]
Information for t-camera users.

I have Wemos 18650 single battery shield.   I have a t-camera v1.6.2.   The t-camera works fine hung of a PC via a powered USB hub.   The t-camera does not appear to want to start up when connected to a fully charged single battery shield.   

I have checked voltages etc.  Voltages present and correct.

The battery shields are sold as "ESP32 shields" but is the problem an amperage thing, seems it might be?   Is this a noise thing?

Understanding there appear to be multiple versions of the single battery shields, there are no markings on the shield to tell me what version it is.

**Comment by Bazmundi** [comment]
This was actually related to ESPHome in the end, and oddly related to a problem #405 of ESPHome, where t-camera v1.6.2 would get into a boot loop if camera code was included.  A number of pins needed to be pulled up with pinMode(x, INPUT_PULLUP) to fix the boot loop.  With the pins setup this way, the t-camera board seems to also now boot on the battery shield without fail.  Pins in question 12..15.  Noting, depending upon your physical t-camera board, the boot problem was better or worse.  I only picked my way through this because I have two boards and they behaved oddly differently, which makes sense if its something around EMI.  The fix for ESPHome actually came from this code base, well done.

**Comment by haldi4803** [comment]
Question to you.
Can you wakeup the device from deepsleep via PIR?
As the documentation states Pin 19 (PIR) is not connected to RTC.


`    Note: PIR Pin not RTC IO, unable to wake from deep sleep
`
