### ISSUE TITLE
camera display?

### ISSUE THREAD

**Issue by richipower** [lewisxhe/esp32-camera-bme280#3]
hello, i am new on the field and i just bought the camera to test it...
I connect the camera with my phone over the wifi but i dont know if i need an additional app for my cellphone? to display the data while connected with the camera?
do i need an extra arduino? just for the visualization?

thanks and greets

**Comment by richipower** [comment]
ah sorry i got it working but in my phone i dont have the last two options:
- Face Detection
- Face Recognition

After color bar comes the camera stream... do i need to do something else?

**Comment by lewisxhe** [comment]
> ah sorry i got it working but in my phone i dont have the last two options:
> 
> * Face Detection
> * Face Recognition
> 
> After color bar comes the camera stream... do i need to do something else?

The reason I hide the bottom button is because I am afraid of being misunderstood because the face recognition feature is not included in the code. If you need to run face recognition, run [esp-who](Https://github.com/espressif/esp-who)
