### ISSUE TITLE
sensor_t struct error on compilation

### ISSUE THREAD

**Issue by sorriso93** [lewisxhe/esp32-camera-bme280#8]
Hello below the errors.
What board should I use to compile it?
Tried TTGO Lora32-OLED v1 and also ESP32-WROOM with ESP32 1.01rc1, 1.01 and 1.01rc2 and 102rc2....

in file included from /Users/yoghibear/Library/Arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp32-camera/esp_camera.h:70:0,
                 from /Users/yoghibear/Desktop/progr esp2866/18_camera_pir/esp32-camera-bme280/esp32-camera-bme280.ino:6:
/Users/yoghibear/Library/Arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp32-camera/sensor.h:83:24: error: conflicting declaration 'typedef struct _sensor sensor_t'
 typedef struct _sensor sensor_t;
                        ^
In file included from /Users/yoghibear/Documents/Arduino/libraries/Adafruit_BME280_Library/Adafruit_BME280.h:29:0,
                 from /Users/yoghibear/Desktop/progr esp2866/18_camera_pir/esp32-camera-bme280/esp32-camera-bme280.ino:5:
/Users/yoghibear/Documents/Arduino/libraries/Adafruit_Sensor/Adafruit_Sensor.h:137:3: note: previous declaration as 'typedef struct sensor_t sensor_t'
 } sensor_t;
   ^
In file included from /Users/yoghibear/Library/Arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp32-camera/esp_camera.h:70:0,
                 from /Users/yoghibear/Desktop/progr esp2866/18_camera_pir/esp32-camera-bme280/esp32-camera-bme280.ino:6:
/Users/yoghibear/Library/Arduino15/packages/esp32/hardware/esp32/1.0.1/tools/sdk/include/esp32-camera/sensor.h:122:3: error: conflicting declaration 'typedef struct _sensor sensor_t'
 } sensor_t;
   ^
In file included from /Users/yoghibear/Documents/Arduino/libraries/Adafruit_BME280_Library/Adafruit_BME280.h:29:0,
                 from /Users/yoghibear/Desktop/progr esp2866/18_camera_pir/esp32-camera-bme280/esp32-camera-bme280.ino:5:
/Users/yoghibear/Documents/Arduino/libraries/Adafruit_Sensor/Adafruit_Sensor.h:137:3: note: previous declaration as 'typedef struct sensor_t sensor_t'
 } sensor_t;
   ^
/Users/yoghibear/Desktop/progr esp2866/18_camera_pir/esp32-camera-bme280/esp32-camera-bme280.ino: In function 'void button1Func()':
esp32-camera-bme280:67:8: error: 'struct sensor_t' has no member named 'set_vflip'
     s->set_vflip(s, en);
        ^
/Users/yoghibear/Desktop/progr esp2866/18_camera_pir/esp32-camera-bme280/esp32-camera-bme280.ino: In function 'void setup()':
esp32-camera-bme280:181:8: error: 'struct sensor_t' has no member named 'set_framesize'
     s->set_framesize(s, FRAMESIZE_QVGA);
        ^
Multiple libraries were found for "WiFi.h"
 Used: /Users/yoghibear/Library/Arduino15/packages/esp32/hardware/esp32/1.0.1/libraries/WiFi
 Not used: /Applications/Sviluppo/Arduino.app/Contents/Java/libraries/WiFi
Multiple libraries were found for "Adafruit_Sensor.h"
 Used: /Users/yoghibear/Documents/Arduino/libraries/Adafruit_Sensor
 Not used: /Users/yoghibear/Documents/Arduino/libraries/Adafruit_Unified_Sensor
exit status 1
'struct sensor_t' has no member named 'set_vflip'

**Comment by sorriso93** [comment]
Sorry, didn't read about the comment out for include adafruit_sensor.h in bme library. now it's fine

**Comment by Patriboom** [comment]
You'll find the answer, I guess, hear:   https://forum.arduino.cc/t/conflicitng-declaration-in-adafruit_sensor-esp32-camera/586568/2
